[package]
name = "rmodbus-tokio-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmodbus = "0.6.1"
tokio = { version = "1.20.4", features = ["full", "time"] }
